version: "3.8"

services:
  node:
    image: node:21-alpine3.17
    container_name: threejs-slides-node
    working_dir: /application
    tty: true
    volumes:
      - .:/application
    ports:
      - "3030:3030"
    restart: unless-stopped
